services:

  # (... paperless services ...) #

  paperless-metadata-ollama-processor:
    container_name: postprocessor
    image: douaberigoale/paperless-metadata-ollama-processor:latest
    ports:
      - "5000:5000"
    environment:
      - PAPERLESS_API_TOKEN=<your-paperless-api-token>
    volumes:
      - /home/alex/bin/paperless/postprocessing:/data
    networks:
      - paperless-network

networks:
  paperless-network:
    external: true