services:

  # (... paperless services ...) #

  paperless-metadata-ollama-processor:
    image: docker.io/library/paperless-postprocessing
    ports:
      - "5000:5000"
    environment:
      - PAPERLESS_API_TOKEN=<your-paperless-api-token>
    volumes:
      - ./data:/data