name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Push Docker image to DockerHub only on release events
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: |
        pytest

  # Job 2: Build and Push Docker image (only on release)
  build-and-push:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (for building Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub using secrets (for pushing the image)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:latest .

    # Step 5: Tag Docker image with release version and push to DockerHub
    - name: Push Docker image with version tag
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:latest ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:${{ github.event.release.tag_name }}
        docker push ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:${{ github.event.release.tag_name }}

    # Step 6: Push Docker image with latest tag
    - name: Push Docker image with latest tag
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:latest
