name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure that all tags are fetched

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the latest Git tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $tag"
          echo "::set-output name=VERSION::$tag"

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:${{ steps.get_tag.outputs.VERSION }} \
            --push .

      - name: Push Docker image with version tag
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:${{ steps.get_tag.outputs.VERSION }}

      - name: Push Docker image with latest tag
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_USERNAME }}/paperless-metadata-processor:latest
